version: '3.8'

services:
  minecraft-server:
    build: .
    image: itzg/minecraft-server
    container_name: mechanical-mastery
    environment:
      CF_API_KEY: '$2a$10$3iDVGIPkrjqtJTc3eBOKl.OrdzFTGRSClsmL0eElP8nRaqQKZF7pO'
      CF_CF_PAGE_URL: 'https://www.curseforge.com/minecraft/modpacks/mechanical-mastery/download/4684136'
      CF_SLUG: 'mechanical-mastery'
      EULA: 'TRUE'
      TYPE: 'AUTO_CURSEFORGE'
      VERSION: '1.18.2'
      MEMORY: '4G'
      ENABLE_ROLLING_LOGS: 'true'
    volumes:
      - ./data:/data
      - ./downloads:/downloads
    ports:
      - '25567:25565'
      - '19567:19565'
    restart: always
